// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clock: typeof import('./../components/Clock/index.vue')['default']
    CountDown: typeof import('./../components/Clock/CountDown.vue')['default']
    MyClock: typeof import('./../components/Clock/MyClock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
